- name: "Obtain Ursula Ops Data from Running Service"
  hosts: "{{ play_hosts }}"
  remote_user: "{{default_user}}"
  gather_facts: no
  any_errors_fatal: true
  tasks:

    - name: "Get Hostname"
      shell:
        cmd: hostname
      register: ursula_hostname

    - name: "Get AWS Identity Information"
      shell:
        cmd: wget -q -O - http://169.254.169.254/latest/dynamic/instance-identity/document
      register: aws_identity_information
      when: cloud_provider == "aws"

    - name: "Get AWS Instance ID"
      set_fact:
        instance_id: "{{ (aws_identity_information.stdout | from_json).instanceId }}"
      when: cloud_provider == "aws"

    - name: "Get AWS Instance Region"
      set_fact:
        instance_region: "{{ (aws_identity_information.stdout | from_json).region }}"
      when: cloud_provider == "aws"

    - name: "Get DO Instance ID"
      become: yes
      shell:
        cmd: curl -s http://169.254.169.254/metadata/v1/id
      register: instance_id
      when: cloud_provider == "digitalocean"

    - name: "Get DO Instance Region"
      become: yes
      shell:
        cmd: curl -s http://169.254.169.254/metadata/v1/region
      register: instance_region
      when: cloud_provider == "digitalocean"

    - name: "Get Ursula Container Name"
      become: yes
      shell:
        cmd: sudo docker ps --no-trunc | grep ursula | cut -f 1 -d " "
      register: ursula_container_name

    - name: "Keystore Password"
      become: yes
      shell:
        cmd: sudo docker inspect {{ursula_container_name.stdout}} --format \{\{range\ .Config.Env\}\}\{\{println\ .\}\}\{\{end\}\} | grep "NUCYPHER_KEYSTORE_PASSWORD" | cut -d "=" -f 2-
      register: keystore_password

    - name: "Operator Password"
      become: yes
      shell:
        cmd: sudo docker inspect {{ursula_container_name.stdout}} --format \{\{range\ .Config.Env\}\}\{\{println\ .\}\}\{\{end\}\} | grep "NUCYPHER_OPERATOR_ETH_PASSWORD" | cut -d "=" -f 2-
      register: operator_password

    - name: "Get Ursula CLI Args"
      shell:
        cmd: sudo docker inspect {{ursula_container_name.stdout}} --format \{\{join\ .Args\ \",\"\}\}
      register: ursula_cli_args

    - name: "Get Docker Image"
      become: yes
      shell:
        cmd: sudo docker inspect {{ursula_container_name.stdout}} --format \{\{.Config.Image\}\}
      register: running_docker_image

    - name: "Get SSH Fingerprint"
      become: yes
      shell:
        cmd: ssh-keygen -l -f ~/.ssh/authorized_keys -E md5 | cut -d " " -f 2 | cut -d ":" -f 2-
      register: ssh_fingerprint

    - name: "Get Ursula JSON Data"
      become: yes
      shell: cat /home/nucypher/nucypher/ursula.json
      register: ursula_config_result

    - name: "Save Ursula config as JSON"
      set_fact:
        ursula_config: "{{ ursula_config_result.stdout | from_json }}"

    - name: "Print Ursula Ops Status"
      ignore_errors: no
      debug:
        msg:
          " InstanceId:             {{instance_id.stdout}}\n
           publicaddress:          {{ursula_config.rest_host}}\n
           host_nickname:          {{ursula_hostname.stdout}}\n
           eth_provider:           {{ursula_config.eth_provider_uri}}\n
           payment_provider:       {{ursula_config.payment_provider}}\n
           payment_network:        {{ursula_config.payment_network}}\n
           docker_image:           {{running_docker_image.stdout}}\n
           operator address:       {{ursula_config.operator_address}}\n
           nickname:               {{ursula_hostname.stdout}}\n
           rest url:               https://{{ursula_config.rest_host}}:{{ursula_config.rest_port}}\n
           _rest-host              {{ursula_config.rest_host}}\n
           _ssh-fingerprint:       {{ssh_fingerprint.stdout}}\n
           _instance-region:       {{instance_region.stdout | upper}}\n
           _domain:                {{ursula_config.domain}}\n
           _keystore-password:     {{keystore_password.stdout}}\n
           _operator-password:     {{operator_password.stdout}}\n
           .cli-args:               {{ursula_cli_args.stdout}}\n
          "
