- name: "Setup tBTCv2 and Random Beacon"
  hosts: "{{ play_hosts }}"
  remote_user: "{{ default_user }}"

- import_playbook: include/setup_user.yml
- import_playbook: include/setup_docker.yml
- import_playbook: include/install_geth.yml
- import_playbook: include/init_operator.yml
- import_playbook: include/get_operator_address.yml
