- name: "Setup Geth"
  hosts: "{{ play_hosts }}"
  remote_user: "{{ default_user }}"
  gather_facts: no
  tasks:
    - name: Keep disk space clean by pruning unneeded docker debris
      become: yes
      shell: docker system prune -af
    
    - name: "create geth data directory"
      become: yes
      file:
        path: "/home/{{ node_user }}/geth/"
        state: directory
        mode: '0755'

    - name: "pull ethereum/client-go:latest"
      become: yes
      docker_image:
        name: "ethereum/client-go:latest"
        source: pull
