- name: "Update Running Ursula"
  hosts: "{{ play_hosts }}"
  remote_user: "{{default_user}}"
  gather_facts: no
  tasks:

    - name: Stop Ursula
      become: yes
      docker_container:
        name: ursula
        state: stopped
      ignore_errors: yes

    - name: Keep disk space clean by pruning unneeded docker debris
      become: yes
      shell: docker system prune -af

    - name: "pull {{ docker_image | default('nucypher/nucypher:latest') }}"
      become: yes
      docker_image:
        name: "{{ docker_image | default('nucypher/nucypher:latest') }}"
        source: pull
        force_source: yes

    - name: Run config migrations
      become: yes
      become_user: nucypher
      command: "docker run -v /home/nucypher:/root/.local/share/ \
        -it {{ docker_image | default('nucypher/nucypher:latest') }} \
        nucypher ursula config migrate"

- import_playbook: run_ursula.yml
